import firebase from 'firebase'
import {
//Prod
REACT_APP_APIKEY_C5BENITO, REACT_APP_AUTHDOMAIN_C5BENITO, 
REACT_APP_DATABASEURL_C5BENITO, REACT_APP_PROJECTID_C5BENITO, 
REACT_APP_STORAGEBUCKET_C5BENITO, 
REACT_APP_MESSAGINGSENDERID_C5BENITO, REACT_APP_APPID_C5BENITO,
// Dev
// REACT_APP_APIKEY_C5BENITODEV,
// REACT_APP_AUTHDOMAIN_C5BENITODEV,
// REACT_APP_DATABASEURL_C5BENITODEV,
// REACT_APP_PROJECT_ID_C5BENITODEV,
// REACT_APP_STORAGEBUCKET_C5BENITODEV,
// REACT_APP_MESSAGINGSENDERID_C5BENITODEV,
// REACT_APP_APPID_C5BENITODEV
} from '../env.js'

/* Production */
var firebaseConfig = {
 apiKey:REACT_APP_APIKEY_C5BENITO,
 authDomain:REACT_APP_AUTHDOMAIN_C5BENITO,
 databaseURL:REACT_APP_DATABASEURL_C5BENITO,
 projectId:REACT_APP_PROJECTID_C5BENITO,
 storageBucket:REACT_APP_STORAGEBUCKET_C5BENITO,
 messagingSenderId:REACT_APP_MESSAGINGSENDERID_C5BENITO,
 appId:REACT_APP_APPID_C5BENITO
};

/* Develop */
// const firebaseConfig = {
//   apiKey:REACT_APP_APIKEY_C5BENITODEV,
//   authDomain:REACT_APP_AUTHDOMAIN_C5BENITODEV,
//   databaseURL:REACT_APP_DATABASEURL_C5BENITODEV,
//   projectId:REACT_APP_PROJECT_ID_C5BENITODEV,
//   storageBucket:REACT_APP_STORAGEBUCKET_C5BENITODEV,
//   messagingSenderId:REACT_APP_MESSAGINGSENDERID_C5BENITODEV,
//   appId:REACT_APP_APPID_C5BENITODEV,
// };

var firebaseC5Benito = firebase

firebaseC5Benito.initializeApp(firebaseConfig, 'c5benito')

export default firebaseC5Benito
