import firebase from 'firebase'
import {REACT_APP_APIKEY_C5VIRTUAL, REACT_APP_AUTHDOMAIN_C5VIRTUAL, REACT_APP_DATABASEURL_C5VIRTUAL,
REACT_APP_PROJECTID_C5VIRTUAL, REACT_APP_STORAGEBUCKET_C5VIRTUAL, REACT_APP_MESSAGINGSENDERID_C5VIRTUAL, REACT_APP_APPID_C5VIRTUAL} from '../env.js'
var firebaseConfig = {
  apiKey:REACT_APP_APIKEY_C5VIRTUAL,
  authDomain:REACT_APP_AUTHDOMAIN_C5VIRTUAL,
  databaseURL:REACT_APP_DATABASEURL_C5VIRTUAL,
  projectId:REACT_APP_PROJECTID_C5VIRTUAL,
  storageBucket:REACT_APP_STORAGEBUCKET_C5VIRTUAL,
  messagingSenderId:REACT_APP_MESSAGINGSENDERID_C5VIRTUAL,
  appId:REACT_APP_APPID_C5VIRTUAL,
};

var firebaseC5 = firebase

firebaseC5.initializeApp(firebaseConfig, 'c5virtual')

export default firebaseC5