import firebase from 'firebase'
import {REACT_APP_APIKEY_CONFIG_WATCHTOWER, REACT_APP_AUTHDOMAIN_CONFIG_WATCHTOWER, REACT_APP_DATABASEURL_CONFIG_WATCHTOWER, 
REACT_APP_PROJECTID_CONFIG_WATCHTOWER, REACT_APP_STORAGEBUCKET_CONFIG_WATCHTOWER, REACT_APP_MESSAGINGSENDERID_CONFIG_WATCHTOWER, 
REACT_APP_APPID_CONFIG_WATCHTOWER} from '../env.js'
const config = {
  apiKey: REACT_APP_APIKEY_CONFIG_WATCHTOWER,
  authDomain: REACT_APP_AUTHDOMAIN_CONFIG_WATCHTOWER,
  databaseURL: REACT_APP_DATABASEURL_CONFIG_WATCHTOWER,
  projectId: REACT_APP_PROJECTID_CONFIG_WATCHTOWER,
  storageBucket: REACT_APP_STORAGEBUCKET_CONFIG_WATCHTOWER,
  messagingSenderId: REACT_APP_MESSAGINGSENDERID_CONFIG_WATCHTOWER,
  appId:REACT_APP_APPID_CONFIG_WATCHTOWER,
};

firebase.initializeApp(config)

export default firebase
