export const SKIP_PREFLIGHT_CHECK = true
export const GENERATE_SOURCEMAP=false

export const REACT_APP_REGION="us-east-1"
export const REACT_APP_ACCESS_KEY_ID="AKIATHM56K3YHWHYDEOK"
export const REACT_APP_SECRET_ACCESS_KEY="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"

export const REACT_APP_APIKEY_SOS="A33317CF-6751-4803-8F92-B0F8DE840B1A"
export const REACT_APP_APISECRET_SOS="FVXqUdLtWaED/qb/i6Te++zklBwYJ8wvfAjmDmlXuLkdgULJ6m1RSGBoEDAGclGqmmjm4T6pLC9OzkeP594GOQ=="
export const REACT_APP_CUSTOMERID_SOS="f99222d6-a2c6-420d-b87e-b605fadd836b"

// config
export const REACT_APP_APIKEY_CONFIG_WATCHTOWER="AIzaSyC1nW0PWv_tl7a3TT1YeZgoohsdhMpRRhA"
export const REACT_APP_AUTHDOMAIN_CONFIG_WATCHTOWER="watchtower-7a145.firebaseapp.com"
export const REACT_APP_DATABASEURL_CONFIG_WATCHTOWER="https://watchtower-7a145.firebaseio.com"
export const REACT_APP_PROJECTID_CONFIG_WATCHTOWER="watchtower-7a145"
export const REACT_APP_STORAGEBUCKET_CONFIG_WATCHTOWER="watchtower-7a145.appspot.com"
export const REACT_APP_MESSAGINGSENDERID_CONFIG_WATCHTOWER="62036046388"
export const REACT_APP_APPID_CONFIG_WATCHTOWER="1:62036046388_config:web:efa0c0881ff8690b"

//configC5

export const REACT_APP_APIKEY_C5VIRTUAL="AIzaSyDVdmSf9QE5KdHNDCSrXwXr3N7QnHaujtg"
export const REACT_APP_AUTHDOMAIN_C5VIRTUAL="c5virtual.firebaseapp.com"
export const REACT_APP_DATABASEURL_C5VIRTUAL="https://c5virtual.firebaseio.com"
export const REACT_APP_PROJECTID_C5VIRTUAL="c5virtual"
export const REACT_APP_STORAGEBUCKET_C5VIRTUAL="c5virtual.appspot.com"
export const REACT_APP_MESSAGINGSENDERID_C5VIRTUAL="816774088533"
export const REACT_APP_APPID_C5VIRTUAL="1:816774088533:web:9ccb8a57de78b7c2"

//C5Benito
export const REACT_APP_APIKEY_C5BENITO="AIzaSyDDq95BbNrQs6WZB-T9B7WTEF2YWr2Ibb0"
export const REACT_APP_AUTHDOMAIN_C5BENITO="c5benito.firebaseapp.com"
export const REACT_APP_DATABASEURL_C5BENITO="https://c5benito.firebaseio.com"
export const REACT_APP_PROJECTID_C5BENITO="c5benito"
export const REACT_APP_STORAGEBUCKET_C5BENITO=""
export const REACT_APP_MESSAGINGSENDERID_C5BENITO="959359457942"
export const REACT_APP_APPID_C5BENITO="1:959359457942:web:cff036937c7515fa"

//C5BenitoDev
export const REACT_APP_APIKEY_C5BENITODEV="AIzaSyDPzqD06v8lAWD3uZy_8A6rfSOy9zXmXIE"
export const REACT_APP_AUTHDOMAIN_C5BENITODEV="c5benitodev.firebaseapp.com"
export const REACT_APP_DATABASEURL_C5BENITODEV="https://c5benitodev.firebaseio.com"
export const REACT_APP_PROJECT_ID_C5BENITODEV="c5benitodev"
export const REACT_APP_STORAGEBUCKET_C5BENITODEV="c5benitodev.appspot.com"
export const REACT_APP_MESSAGINGSENDERID_C5BENITODEV="342714394776"
export const REACT_APP_APPID_C5BENITODEV="1:342714394776:android:3451ef1e07ecd9263a48ed"

//trakinglocationradarcsos
export const REACT_APP_APIKEY_TRACKINGLOCATIONRADARSOS="AIzaSyAwQNoJtyYgvjtQEgsm-SKFUkwf4Gc1qiA"
export const REACT_APP_AUTHDOMAIN_TRACKINGLOCATIONRADARSOS="c5benitosos.firebaseapp.com"
export const REACT_APP_DATABASEURL_TRACKINGLOCATIONRADARSOS="https://c5benitosos.firebaseio.com"
export const REACT_APP_PROJECTID_TRACKINGLOCATIONRADARSOS="c5benitosos"
export const REACT_APP_STORAGEBUCKET_TRACKINGLOCATIONRADARSOS="c5benitosos.appspot.com"
export const REACT_APP_MESSAGINGSENDERID_TRACKINGLOCATIONRADARSOS="886262964822"
export const REACT_APP_APPID_TRACKINGLOCATIONRADARSOS="1:886262964822:web:1142e23c3b3de1a7f391f7"


//devradarsosdev
export const REACT_APP_APIKEY_DEVRADARSOSDEV="AIzaSyBMKleAhkM-RbHMft-sBIOezloY9mOPUxk"
export const REACT_APP_AUTHDOMAIN_DEVRADARSOSDEV="devradarsos.firebaseapp.com"
export const REACT_APP_PROJECTID_DEVRADARSOSDEV="devradarsos"
export const REACT_APP_DATABASEURL_DEVRADARSOSDEV="https://devradarsos.firebaseio.com"
export const REACT_APP_STORAGEBUCKET_DEVRADARSOSDEV="devradarsos.appspot.com"
export const REACT_APP_MESSAGINGSENDERID_DEVRADARSOSDEV="191185099682"
export const REACT_APP_APPID_DEVRADARSOSDEV="1:191185099682:android:508b531d956f4a016bf0fb"

// key para encriptar reset password
export const REACT_APP_ENCRYPT_KEY="R4d4rENKTXxZ2023"